#pragma once
#include "Containers/Map.h"

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "Components/StaticMeshComponent.h"
#include "World/NLTWorldData.h"
#include "World/NLTWorldGenerator.h"
#include "NLTWorldObjectRenderer.generated.h"

/**
 * Visual renderer for the procedural world generated by NLTWorldGenerator.
 * Renders buildings as 3D boxes with type-specific materials (one ISM per
 * building type so each can carry its own material), roads as flat ribbons,
 * and districts as colored ground zones.
 */
UCLASS()
class WORLDENGINE_API ANLTWorldObjectRenderer : public AActor
{
	GENERATED_BODY()

public:
	ANLTWorldObjectRenderer();

	virtual void BeginPlay() override;

	/** Build all visual meshes from a world generation result. */
	UFUNCTION(BlueprintCallable, Category = "NLT|World|Render")
	void BuildFromWorld(const FNLTWorldGenerationResult& WorldResult);

	/** Clear all rendered meshes. */
	UFUNCTION(BlueprintCallable, Category = "NLT|World|Render")
	void ClearWorld();

	bool bRenderDistricts = true;
	bool bRenderRoads = true;
	bool bRenderBuildings = true;
	float BuildingHeightScale = 3.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> ResidentialMaterial;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> CommercialMaterial;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> IndustrialMaterial;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> ParkMaterial;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> OfficeMaterial;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> RoadMaterial;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> DistrictMaterial;

private:
	void RenderBuildings(const TArray<FNLTGeneratedBuilding>& Buildings);
	void RenderRoads(const TArray<FTransform>& RoadPoints, float RoadWidth);
	void RenderDistricts(const TArray<FNLTGeneratedDistrict>& Districts);
	UPROPERTY()
	TMap<FName, TObjectPtr<UInstancedStaticMeshComponent>> BuildingISMs;

	UPROPERTY()
	TObjectPtr<UStaticMeshComponent> PlaneMeshCache;

	UPROPERTY()
	TObjectPtr<UStaticMesh> CubeMeshCache;

	/** Return the ISM component for a given building type (creating it on demand). */
	UInstancedStaticMeshComponent* GetBuildingISM(FName BuildingType);
	UMaterialInterface* GetBuildingMaterial(FName BuildingType) const;
	FLinearColor GetDistrictColor(FName DistrictType) const;

	UPROPERTY()
	TMap<FName, TObjectPtr<UInstancedStaticMeshComponent>> BuildingISMs;

	UPROPERTY()
	TObjectPtr<UStaticMeshComponent> PlaneMeshCache;

	UPROPERTY()
	TObjectPtr<UInstancedStaticMeshComponent> RoadInstances;

	UPROPERTY()
	TArray<TObjectPtr<UStaticMeshComponent>> DistrictMeshes;
};
