#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "Components/StaticMeshComponent.h"
#include "World/NLTWorldData.h"
#include "World/NLTWorldGenerator.h"
#include "NLTWorldObjectRenderer.generated.h"

/**
 * Visual renderer for the procedural world generated by NLTWorldGenerator.
 * Renders buildings as 3D boxes with type-specific materials,
 * roads as flat ribbons, and districts as colored ground zones.
 */
UCLASS()
class WORLDENGINE_API ANLTWorldObjectRenderer : public AActor
{
	GENERATED_BODY()

public:
	ANLTWorldObjectRenderer();

	virtual void BeginPlay() override;

	/** Build all visual meshes from a world generation result. */
	UFUNCTION(BlueprintCallable, Category = "NLT|World|Render")
	void BuildFromWorld(const FNLTWorldGenerationResult& WorldResult);

	/** Clear all rendered meshes. */
	UFUNCTION(BlueprintCallable, Category = "NLT|World|Render")
	void ClearWorld();

	/** Whether to render district zones as colored ground planes. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render")
	bool bRenderDistricts = true;

	/** Whether to render roads. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render")
	bool bRenderRoads = true;

	/** Whether to render buildings. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render")
	bool bRenderBuildings = true;

	/** Height multiplier for buildings (taller = more visible). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render")
	float BuildingHeightScale = 3.0f;

	/** Material for residential buildings. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> ResidentialMaterial;

	/** Material for commercial buildings. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> CommercialMaterial;

	/** Material for industrial buildings. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> IndustrialMaterial;

	/** Material for park areas. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> ParkMaterial;

	/** Material for office buildings. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> OfficeMaterial;

	/** Material for roads. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> RoadMaterial;

	/** Material for district zones. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NLT|World|Render|Materials")
	TObjectPtr<UMaterialInterface> DistrictMaterial;

private:
	/** Render buildings as instanced static meshes. */
	void RenderBuildings(const TArray<FNLTGeneratedBuilding>& Buildings);

	/** Render roads as flat instanced meshes. */
	void RenderRoads(const TArray<FTransform>& RoadPoints, float RoadWidth);

	/** Render districts as colored ground planes. */
	void RenderDistricts(const TArray<FNLTGeneratedDistrict>& Districts);

	/** Get a material for a building type. */
	UMaterialInterface* GetBuildingMaterial(FName BuildingType) const;

	/** Get a color for a district type. */
	FLinearColor GetDistrictColor(FName DistrictType) const;

	UPROPERTY()
	TObjectPtr<UInstancedStaticMeshComponent> BuildingInstances;

	UPROPERTY()
	TObjectPtr<UInstancedStaticMeshComponent> RoadInstances;

	UPROPERTY()
	TArray<TObjectPtr<UStaticMeshComponent>> DistrictMeshes;
};
